import PropTypes from 'prop-types'
import { noop } from '../utils'

export const propTypes = {
  tabs: PropTypes.array,
  disableTabs: PropTypes.arrayOf(PropTypes.number),
  pos: PropTypes.object,
  width: PropTypes.number,
  height: PropTypes.number,
  goToPage: noop,
  activeTab: PropTypes.number,
  renderTab: PropTypes.oneOfType([
    PropTypes.func,
    PropTypes.element,
  ]),
  scrollPosition: PropTypes.string,
  style: PropTypes.object,
  scrollViewStyle: PropTypes.object,
  underlineStyle: PropTypes.object,
  tabDisableStyle: PropTypes.object,
  tabTextDisableStyle: PropTypes.object,
  tabStyle: PropTypes.object,
  tabActiveStyle: PropTypes.object,
  tabTextStyle: PropTypes.object,
  tabTextActiveStyle: PropTypes.object,
  hasUnderline: PropTypes.bool,
  scrollEnabled: PropTypes.bool,
  hasAnimation: PropTypes.bool,
  duration: PropTypes.number,
  vertical: PropTypes.bool,
  isAutoSize: PropTypes.bool,
}

export const defaultProps = {
  tabs: [],
  disableTabs: [],
  pos: null,
  width: undefined,
  height: undefined,
  goToPage: noop,
  activeTab: 0,
  renderTab: null,
  scrollPosition: 'center',
  style: {},
  scrollViewStyle: {},
  underlineStyle: {},
  tabStyle: {},
  tabActiveStyle: {},
  tabTextStyle: {},
  tabTextActiveStyle: {},
  tabDisableStyle: {},
  tabTextDisableStyle: {},
  hasUnderline: true,
  scrollEnabled: true,
  hasAnimation: true,
  duration: 400,
  vertical: true,
  isAutoSize: false,
}
